name: bd_phone_validator
description: A Dart package for validating Bangladeshi phone numbers.
version: 1.0.2
homepage: https://github.com/jihanurrahman33/bd_phone_validator
repository: https://github.com/jihanurrahman33/bd_phone_validator
issue_tracker: https://github.com/jihanurrahman33/bd_phone_validator/issues
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter: # Remove if it's a pure Dart package
    sdk: flutter

dev_dependencies:
  test: ^1.24.0