name: bd_phone_validator
description: A Dart package for validating Bangladeshi phone numbers.
version: 1.0.2  
repository: https://github.com/jihanurrahman33/bd_phone_validator

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.20.0